name: Build & Release (on tag)

on:
  push:
    tags:
      - '*'        # runs for any tag, e.g. v1.0.0

permissions:
  contents: write  # required to create releases & upload assets

jobs:
  build:
    name: Build Electron app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      # ⬇️ run your actual build/packaging command here
      - name: Package
        run: npm run package

      # ⬇️ change this to your build output location
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: electron-build
          path: |
            dist/**
            out/**
            release/**
          if-no-files-found: error

  release:
    name: Create GitHub Release and upload assets
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: electron-build
          path: build-artifacts

      # Creates (or updates) a Release for the current tag and uploads all files.
      - name: Create/Update Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}     # the tag that triggered this workflow
          name: ${{ github.ref_name }}
          body: "Automated release for ${{ github.ref_name }}"
          draft: false
          prerelease: false
          files: |
            build-artifacts/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}